apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  namespace: memory-test
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      limits:
        memory: "612Mi"
      requests:
        memory: "512Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "512M", "--vm-hang", "1"]

